### ISSUE TITLE
jhipster-import-dashboards does not work on OpenShift

### ISSUE THREAD

**Issue by wittwerch** [jhipster/jhipster-console#122]
The jhipster-import-dashboards does not work on OpenShift. It works locally with docker-compose, but on OpenShift somehow the execution context for the user is different.

```
-
  apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: jhipster-import-dashboard
  spec:
    strategy:
      type: Recreate
    replicas: 1
    template:
      metadata:
        labels:
          app: jhipster-import-dashboard
      spec:
        containers:
        - name: jhipster-import-dashboard
          image: jhipster/jhipster-import-dashboards:v4.1.0
          command:
            - 'pwd && env'
          imagePullPolicy: IfNotPresent
          env:
            - name: ELASTICSEARCH_URL
              value: http://jhipster-elasticsearch:9200
        initContainers:
          - name: check-jhipster-elasticsearch-connection
            image: busybox
            command:
            - wget
            - "--spider"
            - "jhipster-elasticsearch:9200/_cluster/health"
```

Once the pod is started, it fails immediately with that error:

`/usr/local/bin/docker-entrypoint: line 13: metricbeat: command not found`
