### ISSUE TITLE
logstash get error Native memory allocation (mmap) failed 

### ISSUE THREAD

**Issue by amirmehdi** [jhipster/jhipster-console#129]
hello,
with this config, I got this error.

```
  jhipster-elasticsearch:
    image: jhipster/jhipster-elasticsearch:v4.1.0
    environment:
      - ES_JAVA_OPTS=-Xms128m -Xmx128m
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
    volumes:
      - log-data:/usr/share/elasticsearch/data
  jhipster-logstash:
    image: jhipster/jhipster-logstash:v4.1.0
    environment:
      - ES_JAVA_OPTS=-Xms128m -Xmx128m
      - INPUT_TCP_PORT=5000
      - INPUT_UDP_PORT=5000
      - ELASTICSEARCH_HOST=jhipster-elasticsearch
      - ELASTICSEARCH_PORT=9200
      - LOGSTASH_DEBUG=false
    ports:
      - 5000:5000
      - 5000:5000/udp
    volumes:
      - /etc/log-conf/:/usr/share/logstash/pipeline/
    depends_on:
      - jhipster-elasticsearch
```

ERROR: 
```
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 986513408 bytes for committing reserved memory.

```

what should I do? 
thankyou
