### ISSUE TITLE
[FEATURE] Database monitoring

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-console#22]
It would be nice to monitor the status of databases and get their error logs in the Console.
Another interesting feature would be to display audits, maybe we could use the [logstash jdbc plugin](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-jdbc.html) for that.

**Comment by PierreBesson** [comment]
I have been able to get mysql console logs messages in Kibana using this in my compose file

```
    app1-mysql:
        container_name: app1-mysql
        image: mysql:5.7.11
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=app1
        command: mysqld --lower_case_table_names=1 --log-error
        logging:
            driver: gelf
            options:
                gelf-address: udp://localhost:5001
                tag: mysql
```

And this in my logstash.conf:
```
input {
    gelf { 
    	port => 5001
	type => docker_logs
    }
}
```

It has the advantage of being able to get logs from any docker container. However those logs would need logstash parsing.
