### ISSUE TITLE
How to handle logstash.conf deploying on Docker Cloud

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/jhipster-console#34]
The issue is: when you run docker-compose it is easy, the logstash.conf file is there, locally on your computer and you map this local directory to your container. 

When you try to run it directly on Docker Cloud through a slack file, what do to? It is not there.

**Comment by PierreBesson** [comment]
I have been thinking about this for sometime. The problem is the following: when deployed to docker (swarm, docker cloud, kubernetes, etc), volume are a headache to deal with as they must be shared between all potential hosts (in docker orchestration systems, we can't know on which host the container will be created).

A workaround is to add the logstash.conf file in the logstash docker image itself.

I have done it here as an experiment: https://github.com/PierreBesson/jhipster-preconfigured-logstash

So the docker-compose set up boils down to this:

```
version: '2'
services:
    elk-elasticsearch:
        image: elasticsearch:2.3.2
        ports:
            - 9200:9200
            - 9300:9300
    elk-logstash:
        image: pbesson/jhipster-preconfigured-logstash
        command: logstash -f /logstash.conf
        ports:
            - 5000:5000/udp
    jhipster-console:
        image: jhipster/jhipster-console:v1.2.1
        ports:
            - 5601:5601
        environment:
            - ELASTICSEARCH_URL=http://elk-elasticsearch:9200
```

No need for complex setup instructions for volumes if you just want to evaluate the console. You would need those only for advanced use cases.

Maybe JHipster should provide its own `jhipster/preconfigured-logstash` image were loading the config from a volume would not be required (still provided as an option). The dockerfile only fits in two line though:
```
FROM logstash:version
ADD logstash.conf /
```

We already have something similar in the `jhipster-console` image for [dashboard loading](https://github.com/jhipster/jhipster-console/blob/master/docker-compose.yml#L26).
One advantage I would see is that it would help keep in sync the logstash and kibana version. Which is a bit tricky to get right... I fear that in the future it could happen that we ship broken ELK in JHipster so this could be a way to fix things (the console is not published to npm so we have ways to correct things).

So the ["upstream" elk.yml](https://github.com/jhipster/generator-jhipster/blob/3d024b8f1d78ac2ffe5ff0093c152f03b40da1b8/generators/docker-compose/templates/elk.yml) would depend on these:

* jhipster/jhipster-console:1.2.1
* preconfigured-logstash:1.2.1
* elasticsearch:version_we_want_to_support

@jdubois would you agree with it ?
