### ISSUE TITLE
zipkin does not work

### ISSUE THREAD

**Issue by anjia0532** [jhipster/jhipster-console#60]
##### **JHipster Version(s)**

```
F:\xx
`-- generator-jhipster@4.4.1

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```yaml
{
  "generator-jhipster": {
    "jhipsterVersion": "4.4.1",
    "baseName": "xx",
    "packageName": "xx",
    "packageFolder": "xx",
    "serverPort": "8082",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "xx",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "skipUserManagement": true,
    "nativeLanguage": "zh-cn",
    "languages": [
      "zh-cn"
    ],
    "clientPackageManager": "yarn"
  }
}
```

##### **Browsers and Operating System**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.11.0.windows.3

node: v7.7.2

npm: 4.1.2

yeoman: 1.8.5

yarn: 0.23.4

`docker-compose.yml`

```yml
version: '2'
services:
    
    gateway-app:
        image: gateway
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://gateway-mysql:3306/gateway?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=gateway-cassandra
            - JHIPSTER_SLEEP=80
            - JHIPSTER_REGISTRY_PASSWORD=admin
        ports:
            - 8080:8080
    gateway-mysql:
        image: mysql:5.7.13
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=gateway
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
    
    xx-app:
        image: xx
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger,zipkin
            - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://xx-mysql:3306/xx?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
    xx-mysql:
        image: mysql:5.7.13
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=xx
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
    
    uaa-app:
        image: uaa
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://uaa-mysql:3306/uaa?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
    uaa-mysql:
        image: mysql:5.7.13
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=uaa
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
    
    
    jhipster-registry:
        image: jhipster/jhipster-registry:v3.0.0
        volumes:
            - ./central-server-config:/central-config
        # By default the JHipster Registry runs with the "prod" and "native"
        # Spring profiles.
        # "native" profile means the filesystem is used to store data, see
        # http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html
        environment:
            - SPRING_PROFILES_ACTIVE=dev,native
            - SECURITY_USER_PASSWORD=admin
            - JHIPSTER_REGISTRY_PASSWORD=admin
            - JHIPSTER_LOGGING_LOGSTASH_ENABLED=true
            - JHIPSTER_LOGGING_LOGSTASH_HOST=jhipster-logstash
            - JHIPSTER_METRICS_LOGS_ENABLED=true
            - JHIPSTER_METRICS_LOGS_REPORTFREQUENCY=60
            # - GIT_URI=https://github.com/jhipster/jhipster-registry/
            # - GIT_SEARCH_PATHS=central-config
        ports:
            - 8761:8761


    jhipster-elasticsearch:
        image: jhipster/jhipster-elasticsearch:v2.0.1
        ports:
            - 9200:9200
            - 9300:9300
        # Uncomment this section to have elasticsearch data persisted to a volume
        #volumes:
        #   - ./log-data:/usr/share/elasticsearch/data
    jhipster-logstash:
        image: jhipster/jhipster-logstash:v2.0.1
        command: logstash -f /conf/logstash.conf
        ports:
            - 5000:5000/udp
        # Uncomment this section to have logstash config loaded from a volume
        #volumes:
        #    - ./log-conf/:/conf
    jhipster-console:
        image: jhipster/jhipster-console:v2.0.1
        ports:
            - 5601:5601
    jhipster-zipkin:
        image: jhipster/jhipster-zipkin:v2.0.1
        ports:
            - 9411:9411
        environment:
            - ES_HOSTS=http://jhipster-elasticsearch:9200
            - ZIPKIN_UI_LOGS_URL=http://localhost:5601/app/kibana#/dashboard/logs-dashboard?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-1h,mode:quick,to:now))&_a=(filters:!(),options:(darkTheme:!f),panels:!((col:1,id:logs-levels,panelIndex:2,row:1,size_x:6,size_y:3,type:visualization),(col:7,columns:!(stack_trace),id:Stacktraces,panelIndex:7,row:1,size_x:4,size_y:3,sort:!('@timestamp',desc),type:search),(col:11,id:Log-forwarding-instructions,panelIndex:8,row:1,size_x:2,size_y:3,type:visualization),(col:1,columns:!(app_name,level,message),id:All-logs,panelIndex:9,row:4,size_x:12,size_y:7,sort:!('@timestamp',asc),type:search)),query:(query_string:(analyze_wildcard:!t,query:'{traceId}')),title:logs-dashboard,uiState:())
```

`application-prod.yml`
```yml
# ...
spring: 
    zipkin: # Use the "zipkin" Maven profile to have the Spring Cloud Zipkin dependencies
        base-url: http://jhipster-zipkin:9411
        enabled: true
        locator:
            discovery:
                enabled: true
# ...

```

```bash
#build docker image
./mvnw package -Pprod,zipkin docker:build

#run the docker services
docker-compose up -d
```

![snipaste20170516_112436](https://cloud.githubusercontent.com/assets/15098916/26088591/a2e4e338-3a2a-11e7-92ed-9a4b705b60c9.png)

the `jhipster-zipkin` env `${ZIPKIN_UI_LOGS_URL}` use `http://localhost:5601`,i changed to `http://jhipster-console:5601` but it was still invalid.
![snipaste20170516_113741](https://cloud.githubusercontent.com/assets/15098916/26088909/612e314a-3a2c-11e7-8063-a927669eeb93.png)

```bash
curl -Xget "http://jhipster-elasticsearch:9200/_search?q=traceId&pretty"
# output
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 10,
    "successful" : 10,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
```

**Comment by PierreBesson** [comment]
I will have a look when I have the time. Thanks for reporting this.

**Comment by PierreBesson** [comment]
I just tested it and it works. Just generated compose files with the `docker-compose` subgen with Console options.
Here is the content of my `central-server-config/application.yml`:

```
#common configuration shared between all applications
configserver:
    name: Docker JHipster Registry
    status: Connected to Consul running in Docker

jhipster:
    security:
        authentication:
            jwt:
                secret: a193412c3f76d49ccf147ff6b64cac39097780d8
    logging:
        logstash: # forward logs to ELK
            enabled: true
            host: jhipster-logstash
    metrics:
        logs: # report metrics in the logs
            enabled: true
            report-frequency: 60 # in seconds

spring:
    zipkin:
        base-url: http://jhipster-zipkin:9411
        enabled: true
```

>the jhipster-zipkin env ${ZIPKIN_UI_LOGS_URL} use http://localhost:5601,i changed to http://jhipster-console:5601 but it was still invalid.

No it should be localhost:5601, this is so that the link between kibana and zipkin works.
If the problem persist. Please upload a sample project to github so I can look into the problem.
