### ISSUE TITLE
jhipster-console not working "out-of-the-box"

### ISSUE THREAD

**Issue by mmesnjak** [jhipster/jhipster-console#76]
Hi,

I tried to recreate jhipster-console installation and I'm not able to get it up and running as described in the documentation: [jhipster monitoring](https://jhipster.github.io/monitoring/)

So before starting I removed all the containers and images related to jhipster from my system including elastic, kibana, zipkin, etc. usin `docker rm` and `docker rmi` commands.
Then I downloaded latest bootstrap `docker-compose.yml` using instructions from the documentation page: 
`curl -O https://raw.githubusercontent.com/jhipster/jhipster-console/master/bootstrap/docker-compose.yml`
I changed logstash port (since I already use 5000 on my docker network) in the `docker-compose.yml` and limited port binding only to localhost:
```
# Production ready docker configuration
version: '2'
services:
    jhipster-elasticsearch:
        image: jhipster/jhipster-elasticsearch
        ports:
            - 127.0.0.1:9200:9200
            - 127.0.0.1:9300:9300
        # Uncomment this as well as the volume section down below
        # to have elasticsearch data persisted to a volume
        # you will need to create a named volume with `docker volume create log-data`
        volumes:
           - log-data:/usr/share/elasticsearch/data

    jhipster-logstash:
        image: jhipster/jhipster-logstash
        environment:
            - INPUT_TCP_PORT=6000
            - INPUT_UDP_PORT=6000
            - ELASTICSEARCH_HOST=jhipster-elasticsearch
            - ELASTICSEARCH_PORT=9200
            - LOGSTASH_DEBUG=false
        ports:
            - 127.0.0.1:6000:6000
            - 127.0.0.1:6000:6000/udp
        # Uncomment this section and add a logstash.conf file in log-conf/
        # to have logstash config loaded from a volume
        #volumes:
        #    - ./log-conf/:/usr/share/logstash/pipeline/

    jhipster-console:
        image: jhipster/jhipster-console
        ports:
            - 127.0.0.1:5601:5601
        environment:
            - ELASTICSEARCH_URL=http://jhipster-elasticsearch:9200

    jhipster-import-dashboards:
        image: jhipster/jhipster-import-dashboards
        environment:
            - ELASTICSEARCH_URL=http://jhipster-elasticsearch:9200
        depends_on:
            - jhipster-elasticsearch

    jhipster-curator:
        image: jhipster/jhipster-curator
        environment:
            - ES_HOST=jhipster-elasticsearch
            - UNIT_COUNT=7
            - UNIT=days

#    jhipster-alerter:
#        image: jhipster/jhipster-alerter
#        #volumes:
#        #    - ../jhipster-alerter/rules/:/opt/elastalert/rules/
#        #    - ../alerts/config.yaml:/opt/elastalert/config.yaml

# Uncomment to use the log-data volume
volumes:
    log-data:
        driver: local

networks:
    default:
        external:
            name: docker_default
```
Before starting services I created a `log-data` docker volume to persist data: `docker volume create log-data`.
I started the services with `docker-compose up -d` with the following output:
```
[user@server jhipster-console]$ docker-compose up -d
Pulling jhipster-elasticsearch (jhipster/jhipster-elasticsearch:latest)...
latest: Pulling from jhipster/jhipster-elasticsearch
e6e5bfbc38e5: Pull complete
8d46f83cd316: Pull complete
145b1d53df05: Pull complete
715fc3bc39a0: Pull complete
85627ecfd2ec: Pull complete
c7d6223729c4: Pull complete
624375db3ae0: Pull complete
48610d65e184: Pull complete
92837f745764: Pull complete
5a47382f3275: Pull complete
0fa7524124f6: Pull complete
Digest: sha256:6fa90b0e28888e3c430b5f69aba83ec8619d36c75cf0476e5b6a25fcc927adb1
Status: Downloaded newer image for jhipster/jhipster-elasticsearch:latest
Pulling jhipster-logstash (jhipster/jhipster-logstash:latest)...
latest: Pulling from jhipster/jhipster-logstash
e6e5bfbc38e5: Already exists
59d1556260fa: Pull complete
91d5266b6948: Pull complete
50b209a6f738: Pull complete
16e5c03f89fa: Pull complete
20e8ad9090bd: Pull complete
0098debe6d27: Pull complete
42304a1347ba: Pull complete
56f1a64a5224: Pull complete
ed6f19558c13: Pull complete
0ba3a51197f4: Pull complete
2cc131675c2e: Pull complete
5a03ea211320: Pull complete
Digest: sha256:0959747545b42b46d2a4bd61bd07cd8f02ffaf748c494da1c8505d1287ebb909
Status: Downloaded newer image for jhipster/jhipster-logstash:latest
Pulling jhipster-curator (jhipster/jhipster-curator:latest)...
latest: Pulling from jhipster/jhipster-curator
90f4dba627d6: Pull complete
19bc0bb0be9f: Pull complete
1a1ae718c97d: Pull complete
f7057ce97169: Pull complete
5f03793b51da: Pull complete
b00fd3c303f4: Pull complete
1c49ff5a7cfd: Pull complete
10e6b005807f: Pull complete
Digest: sha256:23c8104a929dad88bec89f7a5cf5d0058489f1d717b485b6cb312ae6157f821c
Status: Downloaded newer image for jhipster/jhipster-curator:latest
Pulling jhipster-console (jhipster/jhipster-console:latest)...
latest: Pulling from jhipster/jhipster-console
e6e5bfbc38e5: Already exists
3dae5b623dcc: Pull complete
3bfa3fa49f04: Pull complete
e8252b3f6391: Pull complete
a05e5e7cd335: Pull complete
539914b1aae0: Pull complete
4ee696c5d852: Pull complete
bbba454322a3: Pull complete
3fa7a13ec52e: Pull complete
e17da997b2b5: Pull complete
41641300cc0b: Pull complete
af7b9af71de2: Pull complete
Digest: sha256:20e9198df3e00ff539409b60db5eeb1e000947d226f0b30b9d67462ecb33c509
Status: Downloaded newer image for jhipster/jhipster-console:latest
Pulling jhipster-import-dashboards (jhipster/jhipster-import-dashboards:latest)...
latest: Pulling from jhipster/jhipster-import-dashboards
e6e5bfbc38e5: Already exists
ad0b5633606d: Pull complete
30fedc8fe87d: Pull complete
cf9b242aebe1: Pull complete
9b5b6af4bc79: Pull complete
2d4bcefc8e17: Pull complete
d1c8ab80c686: Pull complete
c9d410b21ef7: Pull complete
f65ecb8348ac: Pull complete
Digest: sha256:bee52f5c2df18f8840835b7e93f80e6aa96357a709aea831e41be648d988ca84
Status: Downloaded newer image for jhipster/jhipster-import-dashboards:latest
Creating jhipsterconsole_jhipster-logstash_1 ... 
Creating jhipsterconsole_jhipster-elasticsearch_1 ... 
Creating jhipsterconsole_jhipster-curator_1 ... 
Creating jhipsterconsole_jhipster-console_1 ... 
Creating jhipsterconsole_jhipster-logstash_1
Creating jhipsterconsole_jhipster-elasticsearch_1
Creating jhipsterconsole_jhipster-curator_1
Creating jhipsterconsole_jhipster-console_1 ... done
Creating jhipsterconsole_jhipster-import-dashboards_1 ... 
Creating jhipsterconsole_jhipster-import-dashboards_1 ... done
[user@server jhipster-console]$ 
[user@server jhipster-console]$ 
[user@server jhipster-console]$ 
[user@server jhipster-console]$ docker-compose ps
                    Name                                  Command               State                                   Ports                                  
--------------------------------------------------------------------------------------------------------------------------------------------------------------
jhipsterconsole_jhipster-console_1             /bin/sh -c /usr/local/bin/ ...   Up      127.0.0.1:5601->5601/tcp                                               
jhipsterconsole_jhipster-curator_1             /usr/sbin/crond -f               Up                                                                             
jhipsterconsole_jhipster-elasticsearch_1       /bin/bash bin/es-docker          Up      127.0.0.1:9200->9200/tcp, 127.0.0.1:9300->9300/tcp                     
jhipsterconsole_jhipster-import-dashboards_1   /bin/sh -c ./wait-for-elas ...   Up                                                                             
jhipsterconsole_jhipster-logstash_1            /usr/local/bin/docker-entr ...   Up      5044/tcp, 127.0.0.1:6000->6000/tcp, 127.0.0.1:6000->6000/udp, 9600/tcp 
```

Then I accessed the jhipster console and this is the screen I'm getting:
![screenshot from 2017-08-22 10-57-40](https://user-images.githubusercontent.com/1665509/29557284-dbad90d4-8728-11e7-94c7-99ccb18ba15e.png)
and after selecting `logstash-*` from the drop down I get:
![screenshot from 2017-08-22 10-57-57](https://user-images.githubusercontent.com/1665509/29557304-ef10a274-8728-11e7-8072-2039b03465e2.png)

Then I tried to do dashboard import once again:
```
[user@server jhipster-console]$ docker-compose up jhipster-import-dashboards
jhipsterconsole_jhipster-elasticsearch_1 is up-to-date
jhipsterconsole_jhipster-console_1 is up-to-date
Starting jhipsterconsole_jhipster-import-dashboards_1 ... 
Starting jhipsterconsole_jhipster-import-dashboards_1 ... done
Attaching to jhipsterconsole_jhipster-import-dashboards_1
jhipster-import-dashboards_1  | Waiting for Elasticsearch to startup (max 5min)
jhipster-import-dashboards_1  | {"cluster_name":"docker-cluster","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":5,"active_shards":5,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":5,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":50.0}Importing dashboards
jhipster-import-dashboards_1  | Creating index patterns if not present
jhipster-import-dashboards_1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
jhipster-import-dashboards_1  |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{"_index":".kibana","_type":"index-pattern","_id":"logstash-*","_version":7,"result":"updated","100   215  100   159  100    56   5075   1787 --:--:-- --:--:-- --:--:--  5129
jhipster-import-dashboards_1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
jhipster-import-dashboards_1  |                                  Dload  Upload   Total   Spent    Left  Speed
100    91  100    60  100    31   7310   3777 --:--:-- --:--:-- --:--:--  8571No handler found for uri [/.kibana/config/] and method [PUT]
jhipster-import-dashboards_1  | Import directory /tmp/index-pattern
jhipster-import-dashboards_1  | Import index to /.kibana/index-pattern/logstash-* from /tmp/index-pattern/logstash.json
jhipster-import-dashboards_1  | 
jhipster-import-dashboards_1  | Import directory /tmp/dashboard
jhipster-import-dashboards_1  | Import dashboard /tmp/dashboard/ehcache-dashboard.json
jhipster-import-dashboards_1  | Import visualization /tmp/visualization/ehcache-hits.json
jhipster-import-dashboards_1  | Import visualization /tmp/visualization/ehcache-misses.json
jhipster-import-dashboards_1  | Import dashboard /tmp/dashboard/jvm-dashboard.json
jhipster-import-dashboards_1  | Import visualization /tmp/visualization/log-count.json
jhipster-import-dashboards_1  | Import visualization /tmp/visualization/jvm-total-memory.json
jhipster-import-dashboards_1  | Import visualization /tmp/visualization/jvm-heap-memory.json
jhipster-import-dashboards_1  | Import visualization /tmp/visualization/jvm-threads.json
jhipster-import-dashboards_1  | Import visualization /tmp/visualization/jvm-non-heap-memory.json
jhipster-import-dashboards_1  | Import visualization /tmp/visualization/jvm-memory-average.json
jhipster-import-dashboards_1  | Import visualization /tmp/visualization/jvm-memory-ratio.json
jhipster-import-dashboards_1  | Import dashboard /tmp/dashboard/logs-dashboard.json
jhipster-import-dashboards_1  | Import visualization /tmp/visualization/logs-levels.json
jhipster-import-dashboards_1  | Import search /tmp/search/Stacktraces.json
jhipster-import-dashboards_1  | Import visualization /tmp/visualization/Log-forwarding-instructions.json
jhipster-import-dashboards_1  | Import search /tmp/search/All-logs.json
jhipster-import-dashboards_1  | Import dashboard /tmp/dashboard/metrics-dashboard.json
jhipster-import-dashboards_1  | Import visualization /tmp/visualization/request-rate.json
jhipster-import-dashboards_1  | Import visualization /tmp/visualization/request-rate-for-resources.json
jhipster-import-dashboards_1  | Import visualization /tmp/visualization/metrics-timer.json
jhipster-import-dashboards_1  | Import dashboard /tmp/dashboard/microservices-dashboard.json
jhipster-import-dashboards_1  | Import visualization /tmp/visualization/instances.json
jhipster-import-dashboards_1  | Import visualization /tmp/visualization/applications.json
jhipster-import-dashboards_1  | Import dashboard /tmp/dashboard/performance-dashboard.json
jhipster-import-dashboards_1  | Import visualization /tmp/visualization/request-rate.json
jhipster-import-dashboards_1  | Import visualization /tmp/visualization/request-rate-for-resources.json
jhipster-import-dashboards_1  | Import visualization /tmp/visualization/request-rate-per-resource-per-app.json
jhipsterconsole_jhipster-import-dashboards_1 exited with code 0
[user@server jhipster-console]$
```
What I can see out of this last output that kibana is not properly configured:
```
jhipster-import-dashboards_1  | Creating index patterns if not present
jhipster-import-dashboards_1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
jhipster-import-dashboards_1  |                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{"_index":".kibana","_type":"index-pattern","_id":"logstash-*","_version":7,"result":"updated","100   215  100   159  100    56   5075   1787 --:--:-- --:--:-- --:--:--  5129
jhipster-import-dashboards_1  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
jhipster-import-dashboards_1  |                                  Dload  Upload   Total   Spent    Left  Speed
100    91  100    60  100    31   7310   3777 --:--:-- --:--:-- --:--:--  8571No handler found for uri [/.kibana/config/] and method [PUT]
jhipster-import-dashboards_1  | Import directory /tmp/index-pattern
jhipster-import-dashboards_1  | Import index to /.kibana/index-pattern/logstash-* from /tmp/index-pattern/logstash.json
```

Is there something missing from the instructions on the monitoring page?
